jobs:
  - name: dv-man100
    type: manifest
    steps:
      - IN: dv-image
      - IN: dv-opts
      - IN: dv-params

  - name: box-man100
    type: manifest
    steps:
      - IN: box-image
      - OUT: box-params
