jobs:
  - name: dv-man1
    type: manifest
    steps:
      - GET: dv-image1
      - GET: dv-opts1
      - GET: dv-params1
        applyTo:
          - dv-image1
      - GET: trigger-dv-man1

  - name: box-man1
    type: manifest
    steps:
      - GET: box-image1
      - GET: box-opts1
      #- GET: box-params
