jobs:
  - name: dv-man
    type: manifest
    steps:
      - GET: dv-image
      - GET: dv-opts
      - GET: dv-params
        applyTo:
          - dv-image
      - GET: trigger-dv-man

  - name: box-man
    type: manifest
    steps:
      - GET: box-image
      - GET: box-opts
      - GET: box-params
